binning: 1x1
display_mode: Grayscale
dual_view: false
exposure_time: '100'
scan_objective: 4x
shape: Square
user_directory: Arthur_2025_11_14
start_x: -12868.2001953125
start_y: -1482.0
end_x: 10854.2998046875
end_y: 22240.5
scan_width: '8'
scan_height: '8'
machine_has_dual_view: false
scan_height_length: '26000'
scan_width_length: '45000'
microscope_step_size: '13180'
microscope_objective_size_1: '4'
microscope_objective_size_2: '5'
microscope_objective_size_3: '10'
microscope_objective_size_4: '20'
microscope_objective_size_5: '40'
microscope_objective_size_6: '60'
fluo_objective: 60x
name_model: V1
